modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbguides"
version = "${version}"
displayName = "FTB Guides"
authors = "FTB Team"
description = '''
Guide book mod providing in-game documentation
'''
#logoFile = ""

[[dependencies.ftbguides]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbguides]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbguides]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbguides]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1902.4.1,)"
ordering = "AFTER"
side = "BOTH"
